site_search:
    path:   /search/
    defaults:  { _controller: Networking\ElasticSearchBundle\Controller\DefaultController::search }
    methods: [HEAD, GET, POST]

site_search_de:
    path:   /suche/
    defaults:  { _controller: Networking\ElasticSearchBundle\Controller\DefaultController::search }
    methods: [HEAD, GET, POST]

site_search_fr:
    path:   /recherche/
    defaults:  { _controller: Networking\ElasticSearchBundle\Controller\DefaultController::search }
    methods: [HEAD, GET, POST]


site_search_it:
    path:   /ricercare/
    defaults:  { _controller: Networking\ElasticSearchBundle\Controller\DefaultController::search }
    methods: [HEAD, GET, POST]


site_search_en:
    path:   /search/
    defaults:  { _controller: Networking\ElasticSearchBundle\Controller\DefaultController::search }
    methods: [HEAD, GET, POST]
